# Meta Data for SEO

## Homepage
title = "Seeing Machines"
titleSeparator = "-"
titleAddition = "ITP Fall 2022"
description = "A programming course where we’ll explore various techniques and solutions for tracking and sensing people or objects in space."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["default-image.png"]
ogLocale = "en_US"
domainTLD = "seeingmachines.betamovement.net"
titleHome = "Seeing Machines"

## Twitter Cards
#twitterSite = "@getdoks"
twitterCreator = "@prisonerjohn"

## JSON-LD
schemaType = "Person"
#schemaType = "Organization"
schemaName = "Seeing Machines"
schemaAuthor = "Elie Zananiri"
schemaAuthorTwitter = "https://twitter.com/prisonerjohn"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/prisonerjohn/"
schemaAuthorGitHub = "https://github.com/prisonerjohn"
schemaLocale = "en-US"
schemaLogo = "default-logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "default-image.png"
schemaImageWidth = 1024
schemaImageHeight = 768
#schemaTwitter = "https://twitter.com/getdoks"
#schemaLinkedIn = ""
#schemaGitHub = "https://github.com/h-enk/doks"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://github.com/\">GitHub</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Elie Zananiri"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/prisonerjohn/seeing-machines"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
